enableGlobalCache: true

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.2.cjs
